
### Create a new user

POST http://localhost:3000/users
content-type: application/json

{ "name": "pepe", "surname": "perez", "email" : "admin@admin.com", "password" : "admin", "walletAddress" : "45454fsa54fasrqa" }
